routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\UserLogController;
use App\Http\Controllers\Admin\holidayController;
use App\Http\Controllers\Admin\ReportController;
use App\Http\Controllers\AttendanceController;
use App\Http\Controllers\RolesController;
use App\Http\Controllers\LeaveController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('welcome');
});




Route::group(['middleware' => ['auth', 'isAdmin' ]], function () {
Route::resources([
    // users
    'users' => UserController::class,
    'holidays' => holidayController::class,
    'roles' => RolesController::class,
]);

// Show Trashed users
Route::get('/only-trashed-users', [UserController::class, 'only_trashed_user'])->name('only_trashed_user');

// Recover user
Route::get('/recover-user/{id}', [UserController::class, 'recover_user'])->name('recover_user');

// Delete User Permanently
Route::post('/remove-user-permanently', [UserController::class, 'remove_user_permanently'])->name('remove_user_permanently');

// Logs of specific user
Route::get('/user-logs/{id}', [UserLogController::class, 'show'])->name('user_logs');
Route::get('/user-report/{id}', [ReportController::class, 'report'])->name('user_report');

// All User Attendance Report
Route::get('/all-attendance-report', [ReportController::class, 'all_report'])->name('all_user_report');

// All leave requests applied by the user
Route::get('/all-leave-request', [LeaveController::class, 'all_leave_request'])->name('all_leave_request');

// Change Request Status - will show detail of leave and form
Route::get('/change-request-status/{id}', [LeaveController::class, 'change_request_status'])->name('change_request_status');

// update request status by admin
Route::put('/update-request-status/{id}', [LeaveController::class, 'udpate_request_status'])->name('update-request-status');

// Update/add user Attendance by admin
Route::get('/attendances', [AttendanceController::class, 'all_attendance'])->name('attendances.index');
Route::get('/attendance/{id}/edit', [AttendanceController::class, 'edit_attendance'])->name('attendances.edit');
Route::get('/attendance/create', [AttendanceController::class, 'create_attendance'])->name('attendance.create');
Route::delete('/attendance/{id}', [AttendanceController::class, 'destroy_attendance'])->name('attendance.destroy');
Route::post('/attendance/add', [AttendanceController::class, 'store_attendance'])->name('attendance.store');
// show log report
Route::get('/log-report', [ReportController::class, 'show_log_report'])->name('log_report');


});




// Route::get('/sent-mail', [LeaveController::class, 'sent_mail']);


Route::group(['middleware' => ['auth']], function () {
    Route::get('/dashboard', [App\Http\Controllers\PageController::class, 'dashboard'])->name('dashboard');
    // Route::post('/activity',[App\Http\Controllers\AttendanceController::class, 'Activity'])->name('activity');
});

Route::get('/get-working-hours', [AttendanceController::class, 'get_working_hours'])->name('get_working_hours');

Route::get('/clear-cache', function() {
    Artisan::call('optimize:clear');
    echo Artisan::output();
});

// Route::get('/dashboard', [App\Http\Controllers\HomeController::class, 'index'])->name('dashboard');
// Route::get('dashboard', function(){
//     return "DASHBOARD";
// })->name('dashboard');
Route::get('download', [App\Http\Controllers\PageController::class, 'downloadExcel']);
Auth::routes();

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Illuminate\Database\Eloquent\SoftDeletes;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;
    use SoftDeletes;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'id',
        'name',
        'email',
        'email_verified_at',
        'password',
        'role',
        'status',
        'remember_token',
        'deleted_at',
        'created_at',
        'updated_at',
        'last_login_at',
        'last_login_ip',
        'roles_id',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function UserDetail()
    {
        return $this->hasOne('App\UserDetail', 'users_id', 'id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function UserLog()
    {
        return $this->hasMany('App\UserLog', 'users_id', 'id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function AttendanceDetail()
    {
        return $this->hasMany('App\AttendanceDetail', 'users_id', 'id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function Roles()
    {
        return $this->belongsTo('App\Roles', 'roles_id', 'id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function LeaveRequest()
    {
        return $this->hasMany('App\LeaveRequest', 'user_id', 'id');
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\User;
use App\UserDetail;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\DB;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $users = User::latest()->where('role', '!=', 2)->get();
        return view('admin.users.manage-users', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('admin.users.add-users');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $request->validate([
            'name' => 'required',
            'email' => 'required|email|unique:users',
            'password' => 'required|min:6',
            'phone' => 'required',
            'status' => 'required',
            'address' => 'required',
            'profile_image' => 'required|mimes:jpeg,png,jpg,gif',
            'emergency_contact_name' => 'required',
            'emergency_contact_relation' => 'required',
            'emergency_contact_phone' => 'required',
            'roles_id' => 'required',
            'country' =>'required',
            'city' => 'required',
            'state' => 'required',
        ],

        [
            'name.required' => "Name is required",
            'email.required'  => 'Email is required',
            'password.required' => 'Password is required',
            'password.min' => 'Password must atleast 6 characters',
            'email.email' => 'Invalid email',
            'email.unique' => 'Email already exists',
            'phone.required' => 'Phone is required',
            'status.required' => 'Status is required',
            'address.required' => 'Address is required',
            'profile_image.required' => 'Profile image is required',
            'profile_image.mimes' => 'Only jpeg, png, gif are allowed',
            'emergency_contact_name.required' => 'Emergency contact name is required',
            'emergency_contact_relation.required' => 'Emergency contact relation is required',
            'emergency_contact_phone.required' => 'Emergency contact phone is required',
            'roles_id.required' => 'Designation is required',
            'country' =>'Country is required',
            'city' => 'City is required',
            'state' => 'State is required',
        ]

        );

        $input = $request->all();

        $input['password'] = Hash::make($request->password);

        $user = User::create($input);


        if($request->has('profile_image')){
            $profile_image = $request->file('profile_image');
            $ex = $request->file('profile_image')->getClientOriginalExtension();
            $file_name = time() . rand(1,10) . "." . $ex;
            $path = public_path("/uploads/profile/");
            $profile_image->move($path, $file_name);
            $input['profile_image'] = "uploads/profile/" . $file_name;
        }

        $user->UserDetail()->create($input);

        return redirect()->back()->withInput();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $user = User::findOrFail($id);
        return view('admin.users.show-user', compact('user'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //

        $user = User::findOrFail($id);
        return view('admin.users.edit-users', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $user = User::findOrFail($id);



        $request->validate([
            'name' => 'required',
            'email' => 'required|unique:users,email,' . $id,
            'password' => !empty($request->password) ? 'min:6': 'nullable',
            'phone' => 'required',
            'status' => 'required',
            'address' => 'required',
            'profile_image' => 'mimes:jpeg,png,jpg,gif',
            'emergency_contact_name' => 'required',
            'emergency_contact_relation' => 'required',
            'emergency_contact_phone' => 'required',
            'join_date' => 'required',
            'roles_id' => 'required',
        ],


        [
            'name.required' => "Name is required",
            'email.required'  => 'Email is required',
            'password.min' => 'Password must atleast 6 characters',
            'email.email' => 'Invalid email',
            'email.unique' => 'Email already exists',
            'phone.required' => 'Phone is required',
            'status.required' => 'Status is required',
            'address.required' => 'Address is required',
            'profile_image.mimes' => 'Only jpeg, png, gif are allowed',
            'emergency_contact_name.required' => 'Emergency contact name is required',
            'emergency_contact_relation.required' => 'Emergency contact relation is required',
            'emergency_contact_phone.required' => 'Emergency contact phone is required',
            'join_date.required' => 'Date of Joining is required',
            'roles_id.required' => 'Designation is required',
        ]);


        $input = $request->all();

        if(!empty($input['password'])){
            $input['password'] = Hash::make($request->password);
        }else{
            unset($input['password']);
        }

        DB::beginTransaction();

        $user_updated = $user->update($input);

        $userDetail['phone'] = $request->phone;
        $userDetail['address'] = $request->address;

        $userDetail['emergency_contact_name'] = $request->emergency_contact_name;
        $userDetail['emergency_contact_relation'] = $request->emergency_contact_relation;
        $userDetail['emergency_contact_phone'] = $request->emergency_contact_phone;
        $userDetail['join_date'] = $request->join_date;

        if($request->has('profile_image')){

            $old_img_name = $user->UserDetail->profile_image;

            $profile_image = $request->file('profile_image');
            $ex = $request->file('profile_image')->getClientOriginalExtension();
            $file_name = time() . rand(1,10) . "." . $ex;
            $path = public_path("/uploads/profile/");
            $profile_image->move($path, $file_name);
            $userDetail['profile_image'] = "uploads/profile/" . $file_name;
        }

        $user_detail_updated = $user->UserDetail()->update($userDetail);

        if(!$user_updated && !$user_detail_updated){
            DB::rollback();
            return redirect()->back()->with('status', 'Something went wrong');
        }else{
            DB::commit();
            if($request->has('profile_image')){
                if(File::exists(public_path($old_img_name))){
                    File::delete(public_path($old_img_name));
                }
            }
        }

        return redirect()->back()->with('status', 'updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        User::findOrFail($id)->delete($id);
        return redirect()->back()->with('status', 'Deleted Successfully');
    }

    public function only_trashed_user(){
        $users = User::onlyTrashed()->get();
        return view('admin.users.trashed-users', compact('users'));
    }

    public function recover_user($id){
        $user = User::onlyTrashed()->where('id', $id)->first();
        $user->restore();
        return redirect()->route('users.index')->with('status', 'restored successfully..');
    }

    public function remove_user_permanently(Request $request){
        DB::beginTransaction();
        $user_detail_delete = UserDetail::where('users_id', $request->user_id)->delete();
        $user_delete = User::onlyTrashed()->where('id', $request->user_id)->forceDelete();
        if(!$user_delete && !$user_detail_delete){
            DB::rollback();
            return redirect()->back()->with('error', 'Something went wrong');
        }else{
            DB::commit();
            return redirect()->back()->with('status', 'Deleted permanently');
        }
    }
}

resources/views/admin/users/manage-users.blade.php
@extends('layouts.main')
@push('custom-css')
@endpush

@section('title', 'Manage Users')

@section('breadcrumb-title', 'Users')

@section('main-content')
    <!-- Main content -->
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <a href="{{ route('users.create') }}" class="btn btn-info btn-sm mb-3">Add Users <i
                            class="fa fa-plus-circle" aria-hidden="true"></i></a>
                    <a href="{{ route('only_trashed_user') }}" class="btn btn-danger btn-sm mb-3">Trash <i
                            class="fas fa-trash"></i></a>
                </div>

            </div>
            <div class="row">
                <div class="col-12">

                    <div class="card">
                        <div class="card-header bg-primary">
                            <h3 class="card-title">Manage Users</h3>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <table id="example1" class="table table-bordered table-striped">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Name</th>
                                        <th>Email</th>
                                        <th>Phone No.</th>
                                        <th>Designation</th>
                                        <th>Status</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>

                                <tbody>

                                    @foreach ($users as $user)
                                        <tr>
                                            <td>{{ $loop->iteration }}</td>
                                            <td>{{ $user->name }}</td>
                                            <td>{{ $user->email }}</td>
                                            <td>{{ $user->UserDetail->phone }}</td>
                                            <td>
                                                @if ($user->Roles()->exists())
                                                    <span class="badge badge-warning">{{ $user->Roles->name }}</span>
                                                @endif
                                            </td>
                                            <td>

                                                @if ($user->status == 1)
                                                    <span class="badge badge-success">Active</span>
                                                @elseif ($user->status == 2)
                                                    <span class="badge badge-danger">Inactive</span>
                                                @endif
                                            </td>

                                            <td>
                                                <a href="{{ route('users.edit', ['user' => $user->id]) }}"><span
                                                        class="badge badge-warning p-2"><i
                                                            class="fas fa-edit"></i></span></a>
                                                <a href="{{ route('users.show', ['user' => $user->id]) }}"><span
                                                        class="badge badge-primary p-2"><i
                                                            class="fas fa-eye"></i></span></a>



                                                <a href="javascript:void(0)" id="user-{{ $user->id }}"
                                                    class="delete-user-btn" onclick="confirmDelete({{ $user->id }})">
                                                    <span class="badge badge-danger p-2">
                                                        <i class="fas fa-trash"></i></span>
                                                </a>

                                                <a href="{{ route('user_logs', ['id' => $user->id]) }}">
                                                    <span class="badge badge-secondary p-2 mt-2">
                                                        <i class="fa fa-file" aria-hidden="true"></i>
                                                    </span>
                                                </a>

                                                <a href="{{ route('user_report', ['id' => $user->id]) }}">
                                                    <span class="badge badge-secondary p-2 mt-2">
                                                        <i class="fa fa-file" aria-hidden="true"></i>
                                                    </span>
                                                </a>

                                                <form method="POST"
                                                    action="{{ route('users.destroy', ['user' => $user->id]) }}"
                                                    id="form-{{ $user->id }}">
                                                    @csrf
                                                    @method('DELETE')
                                                </form>




                                            </td>
                                        </tr>
                                    @endforeach

                                </tbody>

                            </table>
                        </div>
                        <!-- /.card-body -->
                    </div>

                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
    <!-- /.content -->
@endsection


@push('footer-script')
    <script>
        $(function() {
            $("#example1").DataTable({
                "responsive": true,
                "lengthChange": false,
                "autoWidth": false,
                // "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
            }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');

            $('#example2').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": false,
                "ordering": true,
                "info": true,
                "autoWidth": false,
                "responsive": true,
            });



        });

        function confirmDelete(user_id) {
            if (confirm("Are you sure you want to delete ? ")) {
                $("#form-" + user_id).submit();
            }
        }
    </script>
@endpush

resources/views/admin/users/trashed-users.blade.php
@extends('layouts.main')
@push('custom-css')
@endpush

@section('title', 'Manage Users')

@section('breadcrumb-title', 'Users')

@section('main-content')
    <!-- Main content -->
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <a href="{{ route('users.create') }}" class="btn btn-info btn-sm mb-3">Add</a>
                </div>
            </div>
            <div class="row">
                <div class="col-12">

                    <div class="card">
                        <div class="card-header bg-primary">
                            <h3 class="card-title">Manage Users</h3>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <table id="example1" class="table table-bordered table-striped">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Name</th>
                                        <th>Email</th>
                                        <th>Phone No.</th>
                                        <th>Created At</th>
                                        <th>Deleted At</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>

                                <tbody>
                                    @foreach ($users as $user)
                                        <tr>
                                            <td>{{ $loop->iteration }}</td>
                                            <td>{{ $user->name }}</td>
                                            <td>{{ $user->email }}</td>
                                            <td>{{ $user->UserDetail->phone }}</td>
                                            <td><span class="badge badge-outline-success p-2">{{ $user->created_at }}</span>
                                            </td>
                                            <td><span class="badge badge-outline-danger  p-2">{{ $user->deleted_at }}</span>
                                            </td>
                                            <td>
                                                <a href="{{ route('recover_user', ['id' => $user->id]) }}"
                                                    class="btn btn-secondary btn-sm">Recover</a>
                                                <a href="javascript:void(0)"
                                                    class="btn btn-danger btn-sm permanent-delete-btn"
                                                    onclick="confirmDelete({{ $user->id }})">Remove
                                                    Permanently</a>
                                                <form action="{{ route('remove_user_permanently') }}" method="POST"
                                                    id="form-{{ $user->id }}">
                                                    @csrf
                                                    @method('POST')
                                                    <input type="hidden" name="user_id" value="{{ $user->id }}">
                                                </form>
                                            </td>

                                        </tr>
                                    @endforeach


                                </tbody>

                            </table>

                        </div>
                        <!-- /.card-body -->
                    </div>

                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
    <!-- /.content -->
@endsection


@push('footer-script')
    <script>
        $(function() {
            $("#example1").DataTable({
                "responsive": true,
                "lengthChange": false,
                "autoWidth": false,
                // "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
            }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');

            $('#example2').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": false,
                "ordering": true,
                "info": true,
                "autoWidth": false,
                "responsive": true,
            });



        });

        function confirmDelete(user_id) {
            if (confirm("Are you sure you want to delete ? ")) {
                $("#form-" + user_id).submit();
            }
        }
    </script>
@endpush